import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import Sidebar from "@/components/Sidebar";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={`dark ${inter.className} flex bg-background`}>
				<section className="2xl:flex-[0.2] lg:flex-[0.3]">
					<Sidebar />
				</section>
				<main className="flex-1">
					{children}
					{/* <Footer /> */}
				</main>
			</body>
		</html>
	);
}
